version: '3'

volumes:
  peer.hyperism.com:
  server.hyperism.com:

networks:
  hyperism_net:
    ipam:
      config:
        - subnet: ${PUBLIC_DATA_NETWORKS}

services:

  # MongoDB
  mongo_db:
    container_name: "mongo_db_container"
    image: mongo
    ports: 
      - 27017:27017
    #   - "${MONGO_PORT}:27017"
    volumes:
      - ./mongodb:/data/db
    # env_file:
    #   - .env
    restart: always
    networks:
      - hyperism_net
  
  # Fiber
  fiber:
    env_file: .env
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
    #   NAME: Truly Mittal
    depends_on:
      - mongo_db
    restart: always
    networks:
      - hyperism_net
  
  peer.hyperism.com:
    extends:
      file: ipfs/docker-compose-p2s.yaml
      service: peer.hyperism.com
    container_name: peer.hyperism.com
    networks:
      - hyperism_net

  server.hyperism.com:
    extends:
      file: ipfs/docker-compose-p2s.yaml
      service: server.hyperism.com
    container_name: server.hyperism.com
    networks:
      - hyperism_net

  cli:
    extends:
      file: ipfs/docker-compose-cli.yaml
      service: cli
    working_dir: /opt/gopath/src/github.com/IBM/IPFSfB/p2s/cli
    depends_on:
      - peer.hyperism.com
      - server.hyperism.com
    networks:
      - hyperism_net