version: '3'

volumes:
  peer.hyperism.com:
  server.hyperism.com:

networks:
  hyperism_net:
    ipam:
      config:
        - subnet: ${PUBLIC_DATA_NETWORKS}

services:

  # MongoDB
  mongo_db:
    container_name: "mongo_db_container"
    image: mongo
    ports: 
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    restart: always
    networks:
      - hyperism_net
  
  # Fiber
  fiber:
    env_file: .env
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
    depends_on:
      - mongo_db
      - ipfs0
    restart: always
    networks:
      - hyperism_net
  
  ipfs0:
    container_name: ipfs0
    image: ipfs/go-ipfs
    environment:
      PORT: 5001
    ports:
      # - 4001:4001 # ipfs swarm - expose if needed/wanted
      - 5001:5001 # ipfs api - expose if needed/wanted
      - 8080:8080 # ipfs gateway - expose if needed/wanted
    volumes:
      - ./compose/ipfs0:/data/ipfs
    networks:
      - hyperism_net
      