version: '3'
services:

  # MongoDB
  mongo_db:
    container_name: "mongo_db_container"
    image: mongo
    ports: 
      - 27017:27017
    #   - "${MONGO_PORT}:27017"
    volumes:
      - ./mongodb:/data/db
    # env_file:
    #   - .env
    restart: always
  
  # Fiber
  fiber:
    env_file: .env
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
    #   NAME: Truly Mittal
    depends_on:
      - mongo_db
    restart: always
